#!/bin/bash --norc

if [[ -z "${EXT_BUILD_ROOT}" ]]; then
  MY_PREFIX=""
else
  MY_PREFIX="${EXT_BUILD_ROOT}/"
fi

PATH="${MY_PREFIX}external/org_linaro_components_toolchain_gcc_armv7/libexec/gcc/arm-linux-gnueabihf/7.4.1:$PATH" \
    exec \
    ${MY_PREFIX}external/org_linaro_components_toolchain_gcc_armv7/bin/arm-linux-gnueabihf-gcc \
    "$@"