# Build Polaris examples and generate releases.
name: Polaris Build

on:
  push:
    # Build on a push to any branch.
    branches:
      - '*'
    # Build on a push of any tag named v* (v1.0, etc.) and generate a release.
    tags:
      - 'v*'

jobs:
  # Build the C++ example applications.
  build_cpp:
    name: Build C++ Applications
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x64, armv7hf, aarch64]
    steps:
    - uses: actions/checkout@v2

    - name: Use Bazel 3.3.0
      uses: abhinavsingh/setup-bazel@v3
      with:
        version: 3.3.0

    - name: Build (native x64)
      if: matrix.arch == 'x64'
      run: |
        bazel build -c opt //examples:*
    - name: Build (cross-compile)
      if: matrix.arch != 'x64'
      run: |
        bazel build -c opt --config=${{ matrix.arch }} //examples:*

    - name: Create artifact
      run: |
        bazel query 'kind("cc_binary", //examples:*)' 2>/dev/null |
        sed -e 's|//examples:|bazel-bin/examples/|' |
        xargs tar czf polaris_examples.tar.gz --transform 's|^bazel-bin|polaris|'

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        path: polaris_examples.tar.gz
        name: polaris_examples.cpp.${{ matrix.arch }}

  # Build the C example applications.
  build_c:
    name: Build C Applications
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [x64]
        os: [ubuntu-latest]
        tool: [make, cmake, bazel]
        compiler: [g++]
        #include:
        #   Windows not currently supported by C library.
        #  - arch: x64
        #    os: windows-latest
        #    tool: cmake
        #    compiler: msvc
    defaults:
      run:
        shell: bash
        working-directory: c
    steps:
    - uses: actions/checkout@v2

    # Environment setup.
    - name: Setup Environment (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        echo "EXT=.exe" >> $GITHUB_ENV

    - name: Setup Environment (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        echo "CXX=/usr/bin/${{ matrix.compiler }}" >> $GITHUB_ENV
        echo "EXT=" >> $GITHUB_ENV

    - name: Install msbuild (Windows)
      if: matrix.os == 'windows-latest'
      uses: microsoft/setup-msbuild@v1.0.2

    # GNU Make build support.
    - name: Build Library And Examples (GNU Make)
      if: matrix.tool == 'make'
      run: |
        make

    # CMake build support.
    - name: Install CMake 3.16.x
      if: matrix.tool == 'cmake'
      uses: jwlawson/actions-setup-cmake@v1.4
      with:
        cmake-version: '3.16.x'

    - name: Setup Build (CMake)
      if: matrix.tool == 'cmake'
      run: |
        mkdir cmake_build
        cd cmake_build
        cmake -DCMAKE_INSTALL_PREFIX=install ..

    - name: Build Library And Examples (CMake, Linux)
      if: matrix.tool == 'cmake' && matrix.os == 'ubuntu-latest'
      run: |
        cd cmake_build
        make
        make install

    - name: Build Library And Examples (CMake, Windows)
      if: matrix.tool == 'cmake' && matrix.os == 'windows-latest'
      run: |
        cd cmake_build
        MSBuild.exe p1_polaris_c_client.sln

    # Bazel build support.
    - name: Use Bazel 3.3.0
      if: matrix.tool == 'bazel'
      uses: abhinavsingh/setup-bazel@v3
      with:
        version: 3.3.0

    - name: Build Library And Examples (Bazel, Native x64)
      if: matrix.tool == 'bazel' && matrix.arch == 'x64'
      run: |
        bazel build -c opt //:polaris_client
        bazel build -c opt //examples:*
    - name: Build Library And Examples (Bazel, Cross-Compile)
      if: matrix.tool == 'bazel' && matrix.arch != 'x64'
      run: |
        bazel build -c opt --config=${{ matrix.arch }} //:polaris_client
        bazel build -c opt --config=${{ matrix.arch }} //examples:*

    # Package artifacts (GNU Make only -- no need to do this for multiple build
    # tools).
    - name: Create artifact
      if: matrix.tool == 'make'
      run: |
        make print_applications |
        xargs tar czfv polaris_examples.tar.gz --transform 's|^|polaris/c/|'

    - name: Upload artifact
      if: matrix.tool == 'make'
      uses: actions/upload-artifact@v1
      with:
        path: c/polaris_examples.tar.gz
        name: polaris_examples.c.${{ matrix.arch }}

  # Create a release only on a tag (not on a branch push).
  release:
    name: Create Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build_cpp, build_c]
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: Create release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

  upload:
    name: Upload Release Assets
    needs: [release]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lang: [cpp, c]
        arch: [x64, armv7hf, aarch64]
        exclude:
          - {lang: c, arch: armv7hf}
          - {lang: c, arch: aarch64}
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: polaris_examples.${{ matrix.lang }}.${{ matrix.arch }}
    - name: Set asset filename
      id: release_info
      env:
        TAG_REF_NAME: ${{ github.ref }}
      run: |
        # polaris_examples-v1.0.0.cpp.aarch64.tar.gz
        echo ::set-output name=file_name::polaris_examples-${TAG_REF_NAME##*/v}.${{ matrix.lang }}.${{ matrix.arch }}.tar.gz
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: polaris_examples.${{ matrix.lang }}.${{ matrix.arch }}/polaris_examples.tar.gz
        asset_name: ${{ steps.release_info.outputs.file_name }}
        asset_content_type: application/tar+gzip
